"use strict";

// Public entry point for git worktrees, diffs, PRs, checkpoints and gc. The code lives in the
// flat worktrees-*.js domain modules; callers keep requiring this file. Mutable exec state
// (setExecFile) and the git read caches have one owner, worktrees-git.js.

// #559 persists this default (10) on every project; 0 is keep-everything.
const { DEFAULT_WORKTREE_RETENTION } = require("./store.js");
const {
  setExecFile,
  PATCH_TRUNCATE,
  resolveGitCommand,
  linuxPathToUnc,
  resolveWorktreeDir,
  GIT_READ_TTL_MS,
  resetGitReadCaches,
  gitTry,
  gitOutAsync,
  gitOutForDiffAsync,
  gitFailureText,
  tailErr,
  gitTryAsync,
} = require("./worktrees-git.js");
const {
  repoDefaultBranch,
  repoDefaultBranchAsync,
  recordedBaseBranch,
  captureLeadSnapshot,
  resolveWorktreeStart,
  listBranches,
  listBranchesAsync,
  defaultBranch,
  defaultBranchAsync,
  slugify,
} = require("./worktrees-branches.js");
const { conflictContext, conflictForecast } = require("./worktrees-conflicts.js");
const { push, assertNoOutboundSecrets } = require("./worktrees-push.js");
const {
  diff,
  listChangedPathsAsync,
  listChangedPaths,
  commit,
  revertFile,
  directoriesFromFiles,
  listFiles,
  lsFiles,
  searchFiles,
} = require("./worktrees-changes.js");
const {
  RETENTION_SWEEP_INTERVAL_MS,
  RETENTION_SWEEP_STARTUP_MS,
  maybeCleanupMergedWorktree,
  sweepOrphanWorktrees,
  gcScan,
  removeGcWorktree,
  gcClean,
  enforceRetention,
  scheduleRetention,
  createRetentionSweeper,
} = require("./worktrees-gc.js");
const {
  removeWorktreeDir,
  mergeWorktree,
  removeWorktree,
  setupWorktree,
  retargetWorktreeBase,
  maybeRenameWorktreeBranch,
  ensureWorktree,
  prepareThreadWorktree,
  clearMissingWorktree,
} = require("./worktrees-lifecycle.js");
const {
  CHECKPOINT_SUBJECT_PREFIX,
  parseShortstat,
  runStats,
  turnDiff,
  maybeCreateCheckpoint,
  listCheckpoints,
  restoreCheckpoint,
} = require("./worktrees-checkpoints.js");
const {
  PR_REFRESH_TIMEOUT_MS,
  GH_TIMEOUT_MS,
  isGitHubRemote,
  isGitHubRemoteAsync,
  ghTryAsync,
  parsePrJson,
  PR_LIST_FIELDS,
  PR_LIST_FIELDS_FALLBACK,
  isUnknownJsonField,
  isGhAuthFailure,
  parsePrListJson,
  listPrsRaw,
  listPrs,
  prStatus,
  parsePrChecksJson,
  parsePrChecksText,
  rollupPrChecks,
  prChecks,
  mergePr,
  mergeFlags,
  mergeOptions,
  isPrRefreshCandidate,
  refreshPrStates,
  createPrStateRefresher,
  PR_TOO_LARGE_PREFIX,
  parseNumstat,
  diffStatVsBase,
  createPr,
} = require("./worktrees-pr.js");
const {
  FORK_READONLY_NOTE,
  DETACHED_READONLY_NOTE,
  parsePrCheckoutView,
  buildPrCheckoutPrompt,
  checkoutPr,
} = require("./worktrees-pr-checkout.js");

module.exports = {
  assertNoOutboundSecrets,
  setupWorktree,
  retargetWorktreeBase,
  listBranches,
  listBranchesAsync,
  recordedBaseBranch,
  repoDefaultBranch,
  repoDefaultBranchAsync,
  captureLeadSnapshot,
  resolveWorktreeStart,
  clearMissingWorktree,
  removeWorktreeDir,
  prepareThreadWorktree,
  gitFailureText,
  maybeRenameWorktreeBranch,
  diff,
  commit,
  revertFile,
  listFiles,
  lsFiles,
  searchFiles,
  directoriesFromFiles,
  listChangedPaths,
  listChangedPathsAsync,
  mergeWorktree,
  conflictContext,
  removeWorktree,
  push,
  createPr,
  PR_TOO_LARGE_PREFIX,
  parseNumstat,
  diffStatVsBase,
  prStatus,
  prChecks,
  mergePr,
  mergeFlags,
  mergeOptions,
  parsePrJson,
  parsePrChecksJson,
  parsePrChecksText,
  rollupPrChecks,
  listPrs,
  listPrsRaw,
  parsePrListJson,
  checkoutPr,
  parsePrCheckoutView,
  buildPrCheckoutPrompt,
  FORK_READONLY_NOTE,
  DETACHED_READONLY_NOTE,
  isUnknownJsonField,
  PR_LIST_FIELDS,
  PR_LIST_FIELDS_FALLBACK,
  refreshPrStates,
  createPrStateRefresher,
  createRetentionSweeper,
  maybeCleanupMergedWorktree,
  sweepOrphanWorktrees,
  gcScan,
  gcClean,
  removeGcWorktree,
  enforceRetention,
  scheduleRetention,
  DEFAULT_WORKTREE_RETENTION,
  ensureWorktree,
  isPrRefreshCandidate,
  isGitHubRemote,
  isGitHubRemoteAsync,
  gitTry,
  resolveGitCommand,
  resolveWorktreeDir,
  linuxPathToUnc,
  defaultBranch,
  defaultBranchAsync,
  gitOutAsync,
  gitOutForDiffAsync,
  setExecFile,
  ghTryAsync,
  GH_TIMEOUT_MS,
  isGhAuthFailure,
  tailErr,
  slugify,
  PATCH_TRUNCATE,
  PR_REFRESH_TIMEOUT_MS,
  RETENTION_SWEEP_INTERVAL_MS,
  RETENTION_SWEEP_STARTUP_MS,
  GIT_READ_TTL_MS,
  resetGitReadCaches,
  maybeCreateCheckpoint,
  listCheckpoints,
  restoreCheckpoint,
  runStats,
  turnDiff,
  conflictForecast,
  parseShortstat,
  gitTryAsync,
  CHECKPOINT_SUBJECT_PREFIX,
};
